/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_boneyard_token1 = 1,
  aux_sym_boneyard_token2 = 2,
  anon_sym_STAR_SLASH = 3,
  aux_sym_inline_note_token1 = 4,
  aux_sym_inline_note_token2 = 5,
  anon_sym_RBRACK_RBRACK = 6,
  sym_text = 7,
  sym_paren_text = 8,
  sym_boneyard_start = 9,
  sym_note_start = 10,
  sym_document = 11,
  sym__element = 12,
  sym_boneyard = 13,
  sym_inline_note = 14,
  aux_sym_document_repeat1 = 15,
  aux_sym_boneyard_repeat1 = 16,
  aux_sym_inline_note_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_boneyard_token1] = "boneyard_token1",
  [aux_sym_boneyard_token2] = "boneyard_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_inline_note_token1] = "inline_note_token1",
  [aux_sym_inline_note_token2] = "inline_note_token2",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_text] = "text",
  [sym_paren_text] = "paren_text",
  [sym_boneyard_start] = "boneyard_start",
  [sym_note_start] = "note_start",
  [sym_document] = "document",
  [sym__element] = "_element",
  [sym_boneyard] = "boneyard",
  [sym_inline_note] = "inline_note",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_boneyard_repeat1] = "boneyard_repeat1",
  [aux_sym_inline_note_repeat1] = "inline_note_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_boneyard_token1] = aux_sym_boneyard_token1,
  [aux_sym_boneyard_token2] = aux_sym_boneyard_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_inline_note_token1] = aux_sym_inline_note_token1,
  [aux_sym_inline_note_token2] = aux_sym_inline_note_token2,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_text] = sym_text,
  [sym_paren_text] = sym_paren_text,
  [sym_boneyard_start] = sym_boneyard_start,
  [sym_note_start] = sym_note_start,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [sym_boneyard] = sym_boneyard,
  [sym_inline_note] = sym_inline_note,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_boneyard_repeat1] = aux_sym_boneyard_repeat1,
  [aux_sym_inline_note_repeat1] = aux_sym_inline_note_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_boneyard_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_boneyard_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_note_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_note_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_text] = {
    .visible = true,
    .named = true,
  },
  [sym_boneyard_start] = {
    .visible = true,
    .named = true,
  },
  [sym_note_start] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_boneyard] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_note] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_boneyard_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_note_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == ']') ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == ']') ADVANCE(4);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_boneyard_token1);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_boneyard_token1);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_boneyard_token2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_inline_note_token1);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_inline_note_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_inline_note_token2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 5, .external_lex_state = 1},
  [2] = {.lex_state = 5, .external_lex_state = 1},
  [3] = {.lex_state = 5, .external_lex_state = 1},
  [4] = {.lex_state = 5, .external_lex_state = 1},
  [5] = {.lex_state = 5, .external_lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_boneyard_token2] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [aux_sym_inline_note_token2] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [sym_paren_text] = ACTIONS(1),
    [sym_boneyard_start] = ACTIONS(1),
    [sym_note_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(12),
    [sym__element] = STATE(2),
    [sym_boneyard] = STATE(2),
    [sym_inline_note] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [sym_text] = ACTIONS(3),
    [sym_paren_text] = ACTIONS(3),
    [sym_boneyard_start] = ACTIONS(5),
    [sym_note_start] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_boneyard_start,
    ACTIONS(7), 1,
      sym_note_start,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      sym_paren_text,
      sym_text,
    STATE(3), 4,
      sym__element,
      sym_boneyard,
      sym_inline_note,
      aux_sym_document_repeat1,
  [20] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(18), 1,
      sym_boneyard_start,
    ACTIONS(21), 1,
      sym_note_start,
    ACTIONS(15), 2,
      sym_paren_text,
      sym_text,
    STATE(3), 4,
      sym__element,
      sym_boneyard,
      sym_inline_note,
      aux_sym_document_repeat1,
  [40] = 1,
    ACTIONS(24), 5,
      sym_paren_text,
      sym_boneyard_start,
      sym_note_start,
      ts_builtin_sym_end,
      sym_text,
  [48] = 1,
    ACTIONS(26), 5,
      sym_paren_text,
      sym_boneyard_start,
      sym_note_start,
      ts_builtin_sym_end,
      sym_text,
  [56] = 4,
    ACTIONS(28), 1,
      aux_sym_boneyard_token1,
    ACTIONS(30), 1,
      aux_sym_boneyard_token2,
    ACTIONS(32), 1,
      anon_sym_STAR_SLASH,
    STATE(8), 1,
      aux_sym_boneyard_repeat1,
  [69] = 4,
    ACTIONS(34), 1,
      aux_sym_inline_note_token1,
    ACTIONS(36), 1,
      aux_sym_inline_note_token2,
    ACTIONS(38), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(9), 1,
      aux_sym_inline_note_repeat1,
  [82] = 4,
    ACTIONS(40), 1,
      aux_sym_boneyard_token1,
    ACTIONS(43), 1,
      aux_sym_boneyard_token2,
    ACTIONS(46), 1,
      anon_sym_STAR_SLASH,
    STATE(8), 1,
      aux_sym_boneyard_repeat1,
  [95] = 4,
    ACTIONS(48), 1,
      aux_sym_inline_note_token1,
    ACTIONS(51), 1,
      aux_sym_inline_note_token2,
    ACTIONS(54), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(9), 1,
      aux_sym_inline_note_repeat1,
  [108] = 3,
    ACTIONS(56), 1,
      aux_sym_boneyard_token1,
    ACTIONS(58), 1,
      aux_sym_boneyard_token2,
    STATE(6), 1,
      aux_sym_boneyard_repeat1,
  [118] = 3,
    ACTIONS(60), 1,
      aux_sym_inline_note_token1,
    ACTIONS(62), 1,
      aux_sym_inline_note_token2,
    STATE(7), 1,
      aux_sym_inline_note_repeat1,
  [128] = 1,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 48,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 82,
  [SMALL_STATE(9)] = 95,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 118,
  [SMALL_STATE(12)] = 128,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boneyard, 3, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_note, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_boneyard_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_boneyard_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_boneyard_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_note_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_note_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_inline_note_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [64] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_paren_text = 0,
  ts_external_token_boneyard_start = 1,
  ts_external_token_note_start = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_paren_text] = sym_paren_text,
  [ts_external_token_boneyard_start] = sym_boneyard_start,
  [ts_external_token_note_start] = sym_note_start,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_paren_text] = true,
    [ts_external_token_boneyard_start] = true,
    [ts_external_token_note_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_fountain_inline_external_scanner_create(void);
void tree_sitter_fountain_inline_external_scanner_destroy(void *);
bool tree_sitter_fountain_inline_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_fountain_inline_external_scanner_serialize(void *, char *);
void tree_sitter_fountain_inline_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fountain_inline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_fountain_inline_external_scanner_create,
      tree_sitter_fountain_inline_external_scanner_destroy,
      tree_sitter_fountain_inline_external_scanner_scan,
      tree_sitter_fountain_inline_external_scanner_serialize,
      tree_sitter_fountain_inline_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "fountain_inline",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
